name: "Lint"

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
      - run: bundle install
      - name: Install Node and packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: bin/lint
